[package]
name = "rmath-rs"
description = "collection of GLSL/HLSL-like vector math to make software-rendering more convenient"
version = "0.1.0"
authors = ["Andrzej Lichnerowicz <andrzej@lichnerowicz.pl>"]
license = "CC0-1.0"
edition = "2018"

[dependencies]
assert_approx_eq = "1.1.0"